#!/bin/sh -e
interactive="${interactive:-"; bash"}"
zypper -n --no-refresh in screen; old=42.3; new=15.0; screen -L -S upgrade sh -c "old=$old; new=$new; zypper -n up --auto-agree-with-licenses --replacefiles && sed -i -e \"s/$old/\\\$releasever/\" /etc/zypp/repos.d/* && sed -i -e \"s@/suse/@/@\" /etc/zypp/repos.d/* && zypper --releasever=$new -n ref && zypper --releasever=$new -n dup --auto-agree-with-licenses --replacefiles --download-in-advance $interactive"
